name: Build and Push to GAR

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REPO_NAME: ${{ secrets.GCP_ARTIFACT_REPO }}
  LOCATION: asia-south1
  IMAGE_NAME: kubernetes-mcp-server

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker $LOCATION-docker.pkg.dev

      - name: Build and Push
        run: |
          IMAGE_TAG=$LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:$GITHUB_SHA
          docker build -t $IMAGE_TAG kubernates-mcp/
          docker push $IMAGE_TAG
          docker tag $IMAGE_TAG $LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:latest
          docker push $LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:latest

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: 'kubernetes-mcp-server'
          region: 'asia-south1'
          image: '${{ env.LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:latest'
          env_vars: |
            K8S_API_TOKEN=${{ secrets.K8S_API_TOKEN }}
            K8S_API_SERVER=${{ secrets.K8S_API_SERVER }}
            K8S_API_CA=${{ secrets.K8S_API_CA }}
            DASHBOARD_API_URL=${{ secrets.DASHBOARD_API_URL }}
